---

platform: linux

image_resource:
  type: docker-image
  source: {repository: lamlouis/pez-docker}

inputs:
  - name: pez-pipelines

run:
  path: pez-pipelines/tasks/haas-1.5-without-nsxt/destroy-edge/task.sh

params:
