---

platform: linux

image_resource:
  type: docker-image
  source: {repository: lamlouis/pez-docker}

inputs:
  - name: pez-pipelines

run:
  path: pez-pipelines/tasks/haas-1.5-without-nsxt/create-edge/task.sh

params:
  HAAS_SLOT:
  HAAS_SLOT_NETWORKS:
  HAAS_SLOT_NAT_IP:
  MGMT_VCENTER_HOST:
  MGMT_VCENTER_USR:
  MGMT_VCENTER_PWD:
  MGMT_VCENTER_DATA_CENTER:
  NSX_EDGE_EXTERNAL_ZONE:
  NSX_EDGE_GEN_NSX_MANAGER_ADDRESS:
  NSX_EDGE_GEN_NSX_MANAGER_ADMIN_USER:
  NSX_EDGE_GEN_NSX_MANAGER_ADMIN_PASSWD:
  NSX_EDGE_GEN_NSX_MANAGER_TRANSPORT_ZONE:
  NSX_EDGE_GEN_EDGE_DATASTORE:
  NSX_EDGE_GEN_EDGE_CLUSTER:
  NSX_EDGE_GEN_NAME:
  ESG_CLI_PASSWORD_1:
  ERT_SSL_CERT:
  ERT_SSL_PRIVATE_KEY:
  ESG_UPLINK_PG:
  ESG_UPLINK_IP:
  ESG_UPLINK_MASK:
  ESG_INTERNAL_PG_1:
  ESG_INTERNAL_IP_1:
  ESG_INTERNAL_LB_IP_1:
  ESG_INTERNAL_MASK_1:
  ESG_INTERNAL_PG_2:
  ESG_INTERNAL_IP_2:
  ESG_INTERNAL_MASK_2:
  ESG_OSPF_AREA:
  ESG_OSPF_PASSWORD:
  ESG_DEFAULT_GATEWAY:
  OM01_IP:
  PAS_GOROUTER_IP:
  PAS_SSHPROXY_IP:
  PAS_TCPROUTER_IP:
  PAS_GOROUTER_VIP:
  PAS_SSHPROXY_VIP:
  PAS_TCPROUTER_VIP:
  OM02_IP:
  PKS_IP:
  JUMPBOX_IP:
