---

platform: linux

image_resource:
  type: docker-image
  source: {repository: lamlouis/pez-docker}

inputs:
  - name: pez-pipelines

run:
  path: pez-pipelines/tasks/haas-1.5-with-nsxt/destroy-edge/task.sh

params:
  MGMT_VCENTER_HOST:
  MGMT_VCENTER_USR:
  MGMT_VCENTER_PWD:
  MGMT_VCENTER_DATA_CENTER:
  NSX_EDGE_GEN_NSX_MANAGER_ADDRESS:
  NSX_EDGE_GEN_NSX_MANAGER_ADMIN_USER:
  NSX_EDGE_GEN_NSX_MANAGER_ADMIN_PASSWD:
  NSX_EDGE_GEN_NSX_MANAGER_TRANSPORT_ZONE:
  NSX_EDGE_GEN_EDGE_DATASTORE:
  NSX_EDGE_GEN_EDGE_CLUSTER:
  NSX_EDGE_GEN_NAME:
  NSX_EDGE_EXTERNAL_ZONE:
  HAAS_SLOT_NAT_IP:
  ESG_INTERNAL_IP_1:
